### ISSUE TITLE
Do not overwrite data on error

### ISSUE THREAD

**Issue by lezioul** [euzu/m3u-filter#51] opened 2024-05-01 20:16 UTC
Hi!

first, i'd like to thank you for your marvellous piece of software : it really suits my needs.

Sometimes, there are errors syncing the inputs (i use xtream and channel list is quite big) : 

```
{"errors": "cant download input url: http://domain.com/player_api.php?username=xxx&password=xxx&action=get_live_streams  => error sending request for url (http://domain.com/player_api.php?username=xxx&password=xxx&act..."}

{"errors": "Failed to download"}
```

I've seen in logs some connection reset and timeouts and i don't know if it's possible to increase timeout but it would be a great thing to prevent errors or incomplete downloads to overwrite actual content.

Best regards,

Lezioul

**Comment by lezioul** [comment] 2024-05-02 09:17
Well, i think i understand what appened : data were overwritten because i changed my filters settings and they were too aggressive.

**Comment by euzu** [comment] 2024-05-03 09:17
@lezioul  can i close this issue ?

**Comment by lezioul** [comment] 2024-05-04 22:15
Yes.

**Closed** 2024-05-04 22:30 UTC

**Comment by lezioul** [comment] 2024-05-05 20:27
Actually, no :(
I've just got the same issue today.

on telegram, i've received these 2 notifications : 

8AM : 
`{"errors": "cant download input url: http://provider.com/player_api.php?username=MyUserName&password=MyPasswd&action=get_live_streams  => request or response body error: error reading a body from connection: unexpected EOF during chunk size line"}`

10PM :
`{"errors": "cant download input url: http://provider.com/player_api.php?username=MyUserName&password=MyPasswd&action=get_live_streams  => error sending request for url (http://provider.com/player_api.php?username=MyUserName&password=MyPasswd&act..."}`

resulting in : 
```
-rw-r--r-- 1 root root       2 mai    5 22:00 cat_live.json
-rw-r--r-- 1 root root    2196 mai    5 22:00 cat_series.json
-rw-r--r-- 1 root root    2630 mai    5 22:00 cat_vod.json
-rw-r--r-- 1 root root 4484665 mai    4 23:58 epg.xml
-rw-r--r-- 1 root root       2 mai    5 22:00 live.json
-rw-r--r-- 1 root root 1899752 mai    4 23:31 series_info.db
-rw-r--r-- 1 root root     228 mai    4 23:31 series_info.idx
-rw-r--r-- 1 root root 4613217 mai    5 22:00 series.json
-rw-r--r-- 1 root root   19835 mai    5 22:03 vod_info.db
-rw-r--r-- 1 root root     118 mai    5 22:03 vod_info.idx
-rw-r--r-- 1 root root 6835852 mai    5 22:00 vod.json
```

json content for cat_live.json and live.json is []

**Comment by kruska7** [comment] 2024-07-17 09:54
@euzu can this be re-opened instead of me creating a new similar issue? The issue is very real for me as I regularly get failed downloads, resulting in lost content on my media players.

I think it would be good if data was not overwritten on error, or if there was some kind of retry mechanism.

As seen in this log, an instant restart of the app resulted in a successful download:

```
bar@bar-macserver:~/mf$ /home/baz/mf/m3u-filter/target/release/m3u-filter -s -p /home/baz/mf/config
[2024-07-17T09:40:06Z INFO  m3u_filter] Log Level INFO
[2024-07-17T09:40:06Z INFO  m3u_filter] Version: 2.0.3
[2024-07-17T09:40:06Z INFO  m3u_filter] Current time: 2024-07-17 11:40:06
[2024-07-17T09:40:06Z INFO  m3u_filter] Working dir: "/home/baz/mf/data"
[2024-07-17T09:40:06Z INFO  m3u_filter] Config dir: "/home/baz/mf/config"
[2024-07-17T09:40:06Z INFO  m3u_filter] Config file: /home/baz/mf/config/config.yml
[2024-07-17T09:40:06Z INFO  m3u_filter] Source file: /home/baz/mf/config/source.yml
[2024-07-17T09:40:06Z INFO  m3u_filter::utils::config_reader] Mappings File: /home/baz/mf/config/mapping.yml
[2024-07-17T09:40:06Z INFO  m3u_filter::utils::config_reader] Api Proxy File: /home/baz/mf/config/api-proxy.yml
[2024-07-17T09:40:06Z INFO  m3u_filter] Server running: http://0.0.0.0:8950
[2024-07-17T09:40:06Z INFO  m3u_filter::api::main_api] Web root: "/home/baz/mf/m3u-filter/frontend/build"
[2024-07-17T09:40:06Z INFO  actix_server::builder] starting 8 workers
[2024-07-17T09:40:06Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2024-07-17T09:40:09Z INFO  m3u_filter::processing::playlist_processor] {"stats": {"name": cuz_in, "type": xtream, "errors": 0, "raw": {"groups": 372, "channels": 21131}, "processed": {"groups": 9, "channels": 221}}}
[2024-07-17T09:40:09Z ERROR m3u_filter::processing::playlist_processor] cant download input url: http://example.domain.me/player_api.php?username=foo&password=qux&action=get_vod_streams  => Request failed error sending request for url (http://example.domain.me/player_api.php?username=foo&password=qux&action=get_vod_streams)
[2024-07-17T09:40:09Z ERROR m3u_filter::processing::playlist_processor] cant download input url: http://example.domain.me/player_api.php?username=foo&password=qux&action=get_series_categories  => Request failed error sending request for url (http://example.domain.me/player_api.php?username=foo&password=qux&action=get_series_categories)
^C[2024-07-17T09:40:29Z INFO  actix_server::server] SIGINT received; starting forced shutdown
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::accept] accept thread stopped
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
[2024-07-17T09:40:29Z INFO  actix_server::worker] shutting down idle worker
bar@bar-macserver:~/mf$ /home/baz/mf/m3u-filter/target/release/m3u-filter -s -p /home/baz/mf/config
[2024-07-17T09:40:52Z INFO  m3u_filter] Log Level INFO
[2024-07-17T09:40:52Z INFO  m3u_filter] Version: 2.0.3
[2024-07-17T09:40:52Z INFO  m3u_filter] Current time: 2024-07-17 11:40:52
[2024-07-17T09:40:52Z INFO  m3u_filter] Working dir: "/home/baz/mf/data"
[2024-07-17T09:40:52Z INFO  m3u_filter] Config dir: "/home/baz/mf/config"
[2024-07-17T09:40:52Z INFO  m3u_filter] Config file: /home/baz/mf/config/config.yml
[2024-07-17T09:40:52Z INFO  m3u_filter] Source file: /home/baz/mf/config/source.yml
[2024-07-17T09:40:52Z INFO  m3u_filter::utils::config_reader] Mappings File: /home/baz/mf/config/mapping.yml
[2024-07-17T09:40:52Z INFO  m3u_filter::utils::config_reader] Api Proxy File: /home/baz/mf/config/api-proxy.yml
[2024-07-17T09:40:52Z INFO  m3u_filter] Server running: http://0.0.0.0:8950
[2024-07-17T09:40:52Z INFO  m3u_filter::api::main_api] Web root: "/home/baz/mf/m3u-filter/frontend/build"
[2024-07-17T09:40:52Z INFO  actix_server::builder] starting 8 workers
[2024-07-17T09:40:52Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2024-07-17T09:41:02Z INFO  m3u_filter::processing::playlist_processor] {"stats": {"name": cuz_in, "type": xtream, "errors": 0, "raw": {"groups": 668, "channels": 115435}, "processed": {"groups": 88, "channels": 33033}}}
```

**Comment by euzu** [comment] 2024-07-17 19:48
@kruska7 i am currently on vacation for one month. I dont have acces to a pc.
I can help you when ı am back home.
