### ISSUE TITLE
Ability to rewrite the host part of the URL in M3U file 

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#17] opened 2023-10-23 11:15 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to use m3u-filte to be able to rewrite the host names of the endpoints in the m3u file or the response from the api so that i can proxy the connection though a local proxy. I can achieve this now using m3u-filter to rewrite a file and iptv-proxy to expose the file but i would like to use xteam and your multiple playlist feature as well and i cannot see how this would be possible.  

**Describe the solution you'd like**
I would like m3u-filter to offer a feature to rewrite the host part of the endpoints in the m3u filer / api response

**Comment by adamsdavis572** [comment] 2023-10-23 11:27
I would like to add that for each m3u xtream playlist id like to have different host names so i can route traffic to the proxies differently. This would allow me to create a playlist that can user the local address of my proxy but also route it externally via a different playlist.

**Comment by euzu** [comment] 2023-10-23 12:02
Hi, can you please give me an example what you want to do ? 

As i understood for m3u , you have an entry like 
```
#EXTINF:-1 tvg-id="" tvg-name="One HD" group-title="GB | One",Public HD
http://my.iptv.provider.com:8080/myuser/token/streamid
```
and you want to change it to 
```
http://one.two.three.tv/myuser/token/streamid
```

in xtream it would be the direct_source  property ?

Is this what you want to do ?

**Comment by euzu** [comment] 2023-10-23 13:36
This is currently only possible if you want to change the host parts of all entries from a `target`.
Each target  has a `rename` block.
``ỳml

   rename:
      - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: http://my.bubble-gum.tv/$2 }
```

When you write this,  each entry of  a target will be replaced.

I will also add this to the mapping part, to more fine grained replacements,  for example each group could be have different hosts.

And what are you missing in `m3u-filter` for serving xtream and m3u-files  with password and username ?

**Comment by euzu** [comment] 2023-10-23 13:47
Ok, i looked into the code and i saw that the url part wasnt implemented :(  I will fix this.

**Comment by euzu** [comment] 2023-10-24 08:21
@adamsdavis572 could you test it ? Can we close the issue ?

My question about `iptv-proxy`, what functionality are you missing in `m3u-filter` ?

**Comment by euzu** [comment] 2023-10-24 10:43
@adamsdavis572 this isnt a build issue, it is a config issue. The config format has changed.
look at line 32 in your `config.yml`

`input` configuration has changed. input is now a list. 

```yaml
sources:
  inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
  targets:
    - name: pl1
      publish: true
      filename: playlist_1.m3u
      type: m3u
      filter: '!ALL_CHAN!'

```

**Comment by adamsdavis572** [comment] 2023-10-24 11:38
So this is the config yml i have been using and im still getting the error

```
api: { host: 127.0.0.1, port: 8901, web_root: /home/m3u-filter/web }
threads: 0
working_dir: /home/m3u-filter/data
# sec  min   hour   day of month   month   day of week   year
schedule: "0  0  8,12,16,20,22,1  *  *  *  *"
sources:
  inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
  targets:
    - name: pl1
      publish: true
      filename: playlist_1.m3u
      type: m3u
      filter: '!ALL_CHAN!'
``` 

However i'm still getting the same error 
`ERROR m3u_filter] M3uFilter error: cant read config file: sources: invalid type: map, expected a sequence at line 7 column 3`

I really hope im not doing something stupid here but the inputs appear to be a list to me?

**Comment by euzu** [comment] 2023-10-24 12:03
Oh sorry,  it is my failure,    sources is a list too,

```yml

sources:
  - inputs:   <-------------  he list dash
    targets:
```

**Comment by adamsdavis572** [comment] 2023-10-24 15:45
Thanks - that worked - ill test properly night :-)

**Comment by euzu** [comment] 2023-10-24 16:06
> Thanks - that worked - ill test properly night :-)

Ok, i am waiting for your response

**Comment by adamsdavis572** [comment] 2023-10-24 18:58
so i have tested the rename rule and it works exactly as needed - many thanks. 

however i cannot get the api-proxy to work. 

i have configure `api-proxy.yml`

```
server:
  protocol: http
  ip: 0.0.0.0
  http_port: 8901
  #https_port: 443
  #rtmp_port:
  timezone: Europe/London
  message: Welcome to m3u-filter
user:
  - target: pl1
    credentials:
      - {username: home, password: xxxxxxx}
```

and `config.yml`

```
api: { host: 0.0.0.0, port: 8901, web_root: "./web" }
threads: 0
......
```
but when i hit `http://<ip-address>:8901/player_api.php?username=home&password=xxxxxxxxx` i get a 400 

```
[2023-10-24T18:47:39Z INFO  actix_web::middleware::logger] 192.168.1.21 "GET /player_api.php?username=home&password=xxxxxxx HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000069
```

but if i hit `http://<ip-address>:8901/get.php?username=home&password=xxxxxxxxx` if returns 200 and the list correctly

any suggestions? thx

**Comment by euzu** [comment] 2023-10-24 19:16
you have defined a user for the target pl1.

Do you have  a target pl1 in the config. yml?

You can only define a user for a target.

And did it run and created the files?

**Comment by euzu** [comment] 2023-10-24 19:33
[Output doc](https://github.com/euzu/m3u-filter#1522-output)

In the README is output described

**Comment by adamsdavis572** [comment] 2023-10-24 19:37
yes apologies this is user error i forgot to include the xtream output. now all endpoints are working  :-) 

however i have one more issue that im not sure how to resolve. 

when i call `http://x.x.x.x:8901/player_api.php?username=home&password=<password>`

i get a successful response 

```
{"user_info":{"active_cons":0,"allowed_output_formats":["ts"],"auth":1,"created_at":1666639623,"exp_date":1729711623,"is_trial":0,"max_connections":1,"message":"Welcome to m3u-filter","password":"dfdfdf","username":"home","status":"Active"},"server_info":{"url":"x.x.x.x","port":8901,"https_port":443,"server_protocol":"http","rtmp_port":1935,"timezone":"Europe/London","timestamp_now":1698175623,"time_now":"2023-10-24 20:27:03"}}
```

however the returned `password` field seems to be hardcoded 

https://github.com/euzu/m3u-filter/blob/76e96093d3dc00fe9cef4984007c2450e78628d8/src/api/xtream_player_api.rs#L25

i assume this is not correct? 

thx

**Comment by adamsdavis572** [comment] 2023-10-24 19:40
Additional info 
This user name and password is used in subsequent calls from the iptv client (smarters iptv) and then fails due to mismatch.

**Comment by euzu** [comment] 2023-10-24 19:55
Ah ok,
i implemented the xtream  api  based on data i have gathered on github. I dont have an api xtream account and couldnt test it well. 

It could be that i forgot to write the right password in the response. İ will fix this tomorrow. Now its a little bit too late.

**Comment by euzu** [comment] 2023-10-25 08:01
@adamsdavis572 i have pushed a new version, please test it.

**Comment by euzu** [comment] 2023-10-25 11:31
@adamsdavis572 when you give me a go, i will create a new release with the new web-ui changes.

**Comment by adamsdavis572** [comment] 2023-10-25 18:19
so `/player_api.php?username=home&password=password` now works correctly and returns the correct info - thank you 👍 

```
{"user_info":{"active_cons":0,"allowed_output_formats":["ts"],"auth":1,"created_at":1666721205,"exp_date":1729793205,"is_trial":0,"max_connections":1,"message":"Welcome to m3u-filter","password":"password","username":"home","status":"Active"},"server_info":{"url":"x.x.x.x","port":8901,"https_port":443,"server_protocol":"http","rtmp_port":1935,"timezone":"Europe/London","timestamp_now":1698257205,"time_now":"2023-10-25 19:06:45"}}
```

however the other, subsequent xtream api calls all fail with a 400 

`/player_api.php?username=home&password=password&action=get_live_categories`
`/player_api.php?username=home&password=password&action=get_vod_categories`
`/player_api.php?username=home&password=password&action=get_series_categories`

error from `/player_api.php?username=home&password=password&action=get_live_categories`

```
[2023-10-25T18:06:39Z INFO  actix_web::middleware::logger] 192.168.1.21 "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000144
```

**Comment by euzu** [comment] 2023-10-25 18:33
@adamsdavis572 i will try to figure out what the problem is. It happens when you make the same api  call in short cycles ?

**Comment by adamsdavis572** [comment] 2023-10-25 18:50
thanks - it happens when you supply any `action` as a query param. how do you provide the mapping from categories to m3u groups? is it inherited from the original xstream api call?

**Comment by euzu** [comment] 2023-10-25 18:55
if your surce is xtream, then the categories and groups are the same.
if you source is m3u the categories are guessed based on the video.extensions  configuration.
 Everyhting that matches the  extension is categorized as Video, anything alse as Live.


I have tested the api and called it with curl, i got no 400 responses.

I try to write more debug logs to figure out what is happening at your side.

**Comment by euzu** [comment] 2023-10-25 19:09
i have added some debug information. You need to set loglevel via command line argument

Following log levels are supported:
- `debug`
- `info` _default_
- `warn`
- `error`
 
Use the `-l` or `-log-level` cli-argument to specify the log-level.

**Comment by adamsdavis572** [comment] 2023-10-25 20:11
ok so im still getting the same 400 and i cant see any more debug info that might give me a clue 

```
$./m3u-filter -s  -a api-proxy.yml -c config.yml -l debug
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] template ALL_CHAN  depends on [US_CHAN, UK_CHAN]
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] [
        PatternTemplate {
            name: "UK_CHAN",
            value: "Group ~ \"^.UK..*\"",
        },
        PatternTemplate {
            name: "US_CHAN",
            value: "Group ~ \"^.US..*\"",
        },
        PatternTemplate {
            name: "ALL_CHAN",
            value: "Group ~ \"^.US..*\" OR Group ~ \"^.UK..*\"",
        },
    ]
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.US..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.UK..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::model::config] Filter: Group ~ "^.US..*" OR Group ~ "^.UK..*"
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.US..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.UK..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::model::config] Filter: Group ~ "^.US..*" OR Group ~ "^.UK..*"
[2023-10-25T19:58:14Z INFO  m3u_filter] working dir: "/home/xxxx/git/m3u-filter/scratch/data"
[2023-10-25T19:58:14Z WARN  m3u_filter::config_reader] cant read mapping file: ./mapping.yml
[2023-10-25T19:58:14Z DEBUG m3u_filter::config_reader] no mapping loaded
[2023-10-25T19:58:14Z DEBUG m3u_filter] web_root: /home/xxxx/git/m3u-filter/scratch/web
[2023-10-25T19:58:14Z INFO  m3u_filter] server running: http://0.0.0.0:8901
[2023-10-25T19:58:14Z INFO  actix_server::builder] starting 2 workers
[2023-10-25T19:58:14Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-10-25T19:58:45Z INFO  actix_web::middleware::logger] 192.168.1.xx "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000114
[2023-10-25T19:58:46Z INFO  actix_web::middleware::logger] 192.168.1.xx "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000067
```

here is the config file im using 

```
api: { host: 0.0.0.0, port: 8901, web_root: ./web }
threads: 0
working_dir: ./data
templates:
  - name: UK_CHAN
    value: Group ~ "^.UK..*"
  - name: US_CHAN
    value: Group ~ "^.US..*"
  - name: ALL_CHAN
    value: >-
      !US_CHAN! OR
      !UK_CHAN!
sources:
  - inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://myportal.live:8080'
      username: Qf9GFSBeu8Up
      password: Qngq4aNjtaVt
    targets:
      - name: pl1
        output:
          - type: xtream
        rename:
          - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: "http://192.168.1.xxxx:8901/$2" }
        sort:
          groups:
            order: asc
        filter: "!ALL_CHAN!"
      - name: pl2
        output:
          - type: xtream
        rename:
          - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: "https://iptvproxy.xxxxx.net/$2" }
        sort:
          groups:
            order: asc
        filter: "!ALL_CHAN!"
```

**Comment by euzu** [comment] 2023-10-25 20:28
Can you check your source code, ı have added  [debug output here](https://github.com/euzu/m3u-filter/blob/7abc80ecf31cba431f31f4d81e36a413f7efd935/src/api/xtream_player_api.rs#L51)

If you dont see this output, the endpoint isnt called.

**Comment by adamsdavis572** [comment] 2023-10-25 20:42
thanks for you patients - user error again 

```
2023-10-25T20:38:46Z DEBUG m3u_filter::api::xtream_player_api] Incoming request UserApiRequest { username: "home", password: "password", token: "", action: "get_live_categories" }
[2023-10-25T20:38:46Z DEBUG m3u_filter::api::xtream_player_api] Could not open file for xtream target: pl1 Cant find collection: pl1/cat_live
[2023-10-25T20:38:46Z INFO  actix_web::middleware::logger] 192.168.1.xx "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000173
[
```

**Comment by euzu** [comment] 2023-10-25 20:50
is there a file under `. data/pl1/cat_live? `

**Comment by adamsdavis572** [comment] 2023-10-25 21:23
thanks for the pointer. i had nothing in the data directory as a result of a permissions issue. all APIs working now :-)

i now need to test the renaming, proxying etc. 

many thanks for your help here. ill let you know the results of the testing tomorrow.

**Comment by adamsdavis572** [comment] 2023-10-25 22:36
Q: if no schedule is defined when will the the call to the source happen to download the playlists? should it happen at startup in server mode? if so this is not happening. when i start in server mode nothing is downloaded to data. i have to start the service in non-server mode to force it to download the playlists. Is this the expected behaviour? thx

**Comment by euzu** [comment] 2023-10-25 22:45
In server mode, the updates only happen on scheduled times. If not defined in config,
it will never happen in server mode.

**Comment by euzu** [comment] 2023-10-25 22:53
I could pıut a manual update button into the web ui, to force updates manually in server mode

**Comment by euzu** [comment] 2023-10-26 09:26
The Web-UI has now a manual update button. You can select the targets to update or  if you do not select any target, all targets will be updated.

@adamsdavis572 can i close this issue ?

**Comment by euzu** [comment] 2023-10-26 09:29
@adamsdavis572 about your question, now i understand the difference to 'iptv-proxy',  'm3u-filter' only serves the metadata not the streams. No  stream request is handled. '/live/home/password/269970.ts'  wont be answered. What do you expect to return for this query ?

**Comment by adamsdavis572** [comment] 2023-10-26 09:40
@euzu i actually wanted to have the request to my iptv provider proxied as i run m3u-filter (currently iptv-proxy) in a container that routes all traffic via a vpn. This then gives me a local endpoint that i can use in my home network or externally that is exposed via a normal HTTPS endpoint that then routes all traffic via a VPN to my IPTV provider. 

i use `pierro777/iptv-proxy`

Now i understand how m3u-filter works i think i should be able to add it as an xtream provider to iptv-proxy and the let the proxy tdo the routing. ill try this shortly. 

BTW im happy for you to close this issue as the original issue is definitely resolved - thank you 👍 

if i have other questions could i ping you? or raise an issue? what would you prefer?

**Comment by euzu** [comment] 2023-10-26 10:59
I have activated discussions. If you have questions you can open a discussion.

**Closed by euzu** 2023-10-26 10:59 UTC
