### ISSUE TITLE
Issue with particular channel not comming trhough

### ISSUE THREAD

**Issue by davidclaeysquinones** [euzu/m3u-filter#89] opened 2024-09-19 06:40 UTC
I'm not 100% sure if what I'm experiencing is a bug or I made some mistake during configuration.

My config looks like this :

source.yml

```
sources:
- inputs:
    - name: pl1
      type: m3u
      persist: 'playlist_1_{}.m3u'
      url: 'http:provider.com/m3u'
      headers:
       User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
  targets:
   - name: livego
     options:
         ignore_logo: true
     output:
       - type: m3u
         filename: pl1.m3u
     sort:
          order: asc
     filter: '(Group ~ ".*Spain.*") OR (Group ~ ".*Belgium.*")'
```

mapping.yml

```yaml
mappings:
  templates:
    - name: spain
      value: 'Group ~ ".*Spain.*"'
    - name: source
      value: 'Url ~ "https?:\/\/(.*?)\/(?P<query>.*)$"'
  mapping:
    - id: spain
      mapper:
        - filter: '!spain!'
          pattern: "!source!"
```

In the list of my provider I can clearly see these channels :

```
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN FHD" tvg-logo="[""]" group-title="Spain",ES: AXN FHD
http://url
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN HD" tvg-logo="[""]" group-title="Spain",ES: AXN HD
http://url
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN White FHD" tvg-logo="[" group-title="Spain",ES: AXN White FHD
http://url
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN WHITE HD" tvg-logo="" group-title="Spain",ES: AXN WHITE HD
http://url
```

However only the _AXN White_ channels come through.
To me it looks like the regex pattern I'm using is correct and that something else is going on.
However if I messed up please tell me and I'll close the issue.

**Comment by euzu** [comment] 2024-09-19 11:47
@davidclaeysquinones  the Problem is your playlist.  as youe can see the  first and second lines have an invalid entry -> `tvg-logo="[""]"`   which causes the m3u-filter to take ES: AXN FD and EX: AXN HD as group.

This means, only the third and fourth lines have the group `Spain`.

Fixing this issue means to change the m3u playlist parsing of m3u-filter to allow invalid  format.

I try to find a solution for this.

**Comment by davidclaeysquinones** [comment] 2024-09-19 12:06
I didn't realize there was an error in my playlist file.
For now I'll add AXN as an addition group filter.
Thanks :)

**Comment by euzu** [comment] 2024-09-19 12:22
@davidclaeysquinones  when you can wait a little bit  i am working on a fix.

**Comment by davidclaeysquinones** [comment] 2024-09-19 12:44
that was quite quick :)
I'm using docker so testing it out will be a bit cumbersome so I'll need some more time

**Comment by euzu** [comment] 2024-09-19 12:58
@davidclaeysquinones the docker image does not have the latest changes which you can see in the CHANGES.md

**Comment by euzu** [comment] 2024-09-19 13:13
@davidclaeysquinones i build a new relase, pull the latest docker image from github

**Comment by davidclaeysquinones** [comment] 2024-09-19 13:24
I've build the Docker image locally.
Right now the channel that was lacking is not anymore.
However channels like _HU: AXN Black_ are now also included.
I've checked twice to make sure my temporary fix is not included on my test environment.

So by example the following Axn channels exist in my playlist

```
#EXTINF:-1 tvg-ID="axn.rs" tvg-name="CRO: AXN Adria" tvg-logo="[" group-title="Hrvatska",CRO: AXN Adria
http://url
#EXTINF:-1 tvg-ID="axnspin.rs" tvg-name="CRO: AXN Spin" tvg-logo="[" group-title="Hrvatska",CRO: AXN Spin
http://url
#EXTINF:-1 tvg-ID="AXN.rs" tvg-name="RS: AXN" tvg-logo="" group-title="Srbija & MN",RS: AXN
http://url
#EXTINF:-1 tvg-ID="axnspin.rs" tvg-name="RS: AXN Spin" tvg-logo="" group-title="Srbija & MN",RS: AXN Spin
http://url
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN FHD" tvg-logo="[""]" group-title="Spain",ES: AXN FHD
http://url
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN HD" tvg-logo="[""]" group-title="Spain",ES: AXN HD
http://url
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: Axn Spain" tvg-logo="[""]" group-title="Spain",ES: Axn Spain
http://url
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN White FHD" tvg-logo="[" group-title="Spain",ES: AXN White FHD
http://url
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN WHITE HD" tvg-logo="" group-title="Spain",ES: AXN WHITE HD
http://url
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: Axn White Spain" tvg-logo="[""]" group-title="Spain",ES: Axn White Spain
http://url
#EXTINF:-1 tvg-ID="axn.de" tvg-name="DE: AXN FHD" tvg-logo="[" group-title="Germany",DE: AXN FHD
http://url
#EXTINF:-1 tvg-ID="axn.de" tvg-name="DE: AXN HD" tvg-logo="[" group-title="Germany",DE: AXN HD
http://url
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN FHD" tvg-logo="" group-title="Portugal",PT: AXN FHD
http://url
#EXTINF:-1 tvg-ID="axn.pt" tvg-name="PT: AXN HD" tvg-logo="[" group-title="Portugal",PT: AXN HD
http://url
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN MOVIES FHD" tvg-logo="" group-title="Portugal",PT: AXN MOVIES FHD
http://url
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN MOVIES HD" tvg-logo="" group-title="Portugal",PT: AXN MOVIES HD
http://url
#EXTINF:-1 tvg-ID="axnwhite.pt" tvg-name="PT: AXN WHITE FHD" tvg-logo="[" group-title="Portugal",PT: AXN WHITE FHD
http://url
#EXTINF:-1 tvg-ID="axnwhite.pt" tvg-name="PT: AXN WHITE HD" tvg-logo="[" group-title="Portugal",PT: AXN WHITE HD
http://url
#EXTINF:-1 tvg-ID="axn.pt" tvg-name="PT: AXN Movies FHD" tvg-logo="[" group-title="Portugal",PT: AXN Movies FHD
http://url
#EXTINF:-1 tvg-ID="axnblack.pt" tvg-name="PT: AXN Movies HD" tvg-logo="[" group-title="Portugal",PT: AXN Movies HD
http://url
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN" tvg-logo="" group-title="Slovakia",SK: AXN
http://url
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN Black" tvg-logo="" group-title="Slovakia",SK: AXN Black
http://url
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN White" tvg-logo="" group-title="Slovakia",SK: AXN White
http://url
#EXTINF:-1 tvg-ID="axnblack.pl" tvg-name="PL: AXN Black" tvg-logo="" group-title="Poland",PL: AXN Black
http://url
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN" tvg-logo="" group-title="Hungary",HU: AXN
http://url
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN Black" tvg-logo="[""]" group-title="Hungary",HU: AXN Black
http://url
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN White" tvg-logo="[""]" group-title="Hungary",HU: AXN White
http://url
```

**Comment by euzu** [comment] 2024-09-19 14:03
@davidclaeysquinones yes this is correct, because you take  use AXN as filter,  you should use `Group` now with the latest docker image or master branch builds, or use for example  `Group ~ "^ES: AXN.*"` as filter

**Comment by euzu** [comment] 2024-09-19 14:29
@davidclaeysquinones  i took the playlist you pasted here. And i got only the 6 channels from spain

`source.yml`

```yaml
sources:
- inputs:
    - name: pl1
      type: m3u
      persist: 'playlist_1_{}.m3u'
      url: 'http://localhost:7000/quinones.m3u'
      headers:
       User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
  targets:
   - name: livego
     options:
         ignore_logo: true
     output:
       - type: m3u
         filename: pl1.m3u
     sort:
       order: asc
     filter: '(Group ~ ".*Spain.*") OR (Group ~ ".*Belgium.*")'
     mapping:
       - spain
```

`mapping.yml`

```yaml
---
mappings:
  templates:
    - name: spain
      value: 'Group ~ ".*Spain.*"'
    - name: source
      value: 'Url ~ "https?:\/\/(.*?)\/(?P<query>.*)$"'
  mapping:
    - id: spain
      mapper:
        - filter: '!spain!'
          pattern: '!source!'
```

`playlist`
```m3u
#EXTM3U
#EXTINF:-1 tvg-ID="axn.rs" tvg-name="CRO: AXN Adria" tvg-logo="[" group-title="Hrvatska",CRO: AXN Adria
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnspin.rs" tvg-name="CRO: AXN Spin" tvg-logo="[" group-title="Hrvatska",CRO: AXN Spin
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="AXN.rs" tvg-name="RS: AXN" tvg-logo="" group-title="Srbija & MN",RS: AXN
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnspin.rs" tvg-name="RS: AXN Spin" tvg-logo="" group-title="Srbija & MN",RS: AXN Spin
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN FHD" tvg-logo="[""]" group-title="Spain",ES: AXN FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: AXN HD" tvg-logo="[""]" group-title="Spain",ES: AXN HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.es" tvg-name="ES: Axn Spain" tvg-logo="[""]" group-title="Spain",ES: Axn Spain
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN White FHD" tvg-logo="[" group-title="Spain",ES: AXN White FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: AXN WHITE HD" tvg-logo="" group-title="Spain",ES: AXN WHITE HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnwhite.es" tvg-name="ES: Axn White Spain" tvg-logo="[""]" group-title="Spain",ES: Axn White Spain
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.de" tvg-name="DE: AXN FHD" tvg-logo="[" group-title="Germany",DE: AXN FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.de" tvg-name="DE: AXN HD" tvg-logo="[" group-title="Germany",DE: AXN HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN FHD" tvg-logo="" group-title="Portugal",PT: AXN FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.pt" tvg-name="PT: AXN HD" tvg-logo="[" group-title="Portugal",PT: AXN HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN MOVIES FHD" tvg-logo="" group-title="Portugal",PT: AXN MOVIES FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="NULL" tvg-name="PT: AXN MOVIES HD" tvg-logo="" group-title="Portugal",PT: AXN MOVIES HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnwhite.pt" tvg-name="PT: AXN WHITE FHD" tvg-logo="[" group-title="Portugal",PT: AXN WHITE FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnwhite.pt" tvg-name="PT: AXN WHITE HD" tvg-logo="[" group-title="Portugal",PT: AXN WHITE HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axn.pt" tvg-name="PT: AXN Movies FHD" tvg-logo="[" group-title="Portugal",PT: AXN Movies FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnblack.pt" tvg-name="PT: AXN Movies HD" tvg-logo="[" group-title="Portugal",PT: AXN Movies HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN" tvg-logo="" group-title="Slovakia",SK: AXN
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN Black" tvg-logo="" group-title="Slovakia",SK: AXN Black
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="" tvg-name="SK: AXN White" tvg-logo="" group-title="Slovakia",SK: AXN White
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="axnblack.pl" tvg-name="PL: AXN Black" tvg-logo="" group-title="Poland",PL: AXN Black
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN" tvg-logo="" group-title="Hungary",HU: AXN
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN Black" tvg-logo="[""]" group-title="Hungary",HU: AXN Black
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-ID="AXN (HD).hu" tvg-name="HU: AXN White" tvg-logo="[""]" group-title="Hungary",HU: AXN White
http://localhost:7000/quinones/secret/90002
```

And the result is:

```m3u
#EXTM3U
#EXTINF:-1 tvg-id="axn.es" tvg-name="ES: AXN FHD" group-title="Spain",ES: AXN FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-id="axn.es" tvg-name="ES: AXN HD" group-title="Spain",ES: AXN HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-id="axn.es" tvg-name="ES: Axn Spain" group-title="Spain",ES: Axn Spain
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-id="axnwhite.es" tvg-name="ES: AXN White FHD" group-title="Spain",ES: AXN White FHD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-id="axnwhite.es" tvg-name="ES: AXN WHITE HD" group-title="Spain",ES: AXN WHITE HD
http://localhost:7000/quinones/secret/90002
#EXTINF:-1 tvg-id="axnwhite.es" tvg-name="ES: Axn White Spain" group-title="Spain",ES: Axn White Spain
http://localhost:7000/quinones/secret/90002
```


There are only Spain channels.  How are you accessing the generated playlist ?

**Comment by davidclaeysquinones** [comment] 2024-09-19 14:58
I'm accesting the playlist through the api.
Like so _http://localhost:8901/get.php?token=abcde_

**Comment by euzu** [comment] 2024-09-19 15:04
@davidclaeysquinones yes this is the right way. Something in your configuration must be different than what i have used.
Because i get the right result, nothing wrong.


if you dont plan to access the files then you should not use 
-  `filename: pl1.m3u`    the processed result
-  `persist: 'playlist_1_{}.m3u'`   the original playlist

The api to access the playlist does not use the persisted m3u files.   This files are only keep a copy of the provider playlist and copy the result to somewhere else.

**Comment by davidclaeysquinones** [comment] 2024-09-19 15:13
The playlist of my provider is trash.
I wouldn't mind sending you the complete file through PM

**Comment by davidclaeysquinones** [comment] 2024-09-19 16:03
Can I have your email ?

**Comment by euzu** [comment] 2024-09-19 16:07
euzu@byom.de

**Comment by davidclaeysquinones** [comment] 2024-09-19 16:12
I just send you the playlist through Wetransfer

**Comment by euzu** [comment] 2024-09-19 16:14
i did not receive any link , where did you send it ?

**Comment by davidclaeysquinones** [comment] 2024-09-19 16:20
I send it to [euzu@byom.de](mailto:euzu@byom.de)

**Comment by euzu** [comment] 2024-09-19 16:26
sorry i dont have access to the email address currently.

can you send it to euzu@jaga.email please

**Comment by davidclaeysquinones** [comment] 2024-09-19 17:32
I've sent it to the new address

**Comment by davidclaeysquinones** [comment] 2024-09-19 19:28
I've sent it again , did you receive it ?

**Comment by euzu** [comment] 2024-09-19 19:30
Yes i received it, i will look at it tomorrow.

**Comment by euzu** [comment] 2024-09-20 05:34
@davidclaeysquinones  it works as expected. i am getting 4 groups
spain, spain sports events, belgium and belgium sports events.

I dont know what you are doing wrong, but the config i used is the same i posted above.

**Comment by davidclaeysquinones** [comment] 2024-09-20 06:35
I forced a download of the playlist and the issue seems to have disappeared

**Comment by euzu** [comment] 2024-09-20 06:45
@davidclaeysquinones ok then i close this issue

**Closed by euzu** 2024-09-20 06:45 UTC
